### ISSUE TITLE
同样的insert into select SQL，在navicat中可以插入成功，但用python 执行报错pymysql.err.InternalError: (9500, 'transaction too large, len:300001')

### ISSUE THREAD

**Issue by xqwbx163** [pingcap/docs-cn#1457]
navicat 执行SQL语句
`set @@session.tidb_batch_insert=1
> OK
> 时间: 0.037s

insert into xxxxx select ..........
from xxxxxxxx where orderday='2019-06-13' group by orderday,areaid,storeno,username
> Affected rows: 651175
> 时间: 73.739s`

同样的SQL语句用python 执行就报错
`
sql= '''
 set @@session.tidb_batch_insert=1;
insert into xxx   select   ...................
from xxxxx  where orderday='2019-06-08' group by orderday,areaid,storeno,username; 
'''
cursor_tidb.execute(sql)
conn_tidb.commit()`

-- ERROR code 

Traceback (most recent call last):
  File "E:/python_pycharm/test_insert_sql.py", line 27, in <module>
    cursor_tidb.execute(sql)
  File "C:\Users\Administrator\PycharmProjects\untitled2\venv\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Users\Administrator\PycharmProjects\untitled2\venv\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Users\Administrator\PycharmProjects\untitled2\venv\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\Administrator\PycharmProjects\untitled2\venv\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\Users\Administrator\PycharmProjects\untitled2\venv\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\Administrator\PycharmProjects\untitled2\venv\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Users\Administrator\PycharmProjects\untitled2\venv\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Administrator\PycharmProjects\untitled2\venv\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (9500, 'transaction too large, len:300001')

Process finished with exit code 1

求助一下为啥？

**Comment by xqwbx163** [comment]
我找到问题了，是python pymysql提交任务的时候，不会auto commit是关闭的导致所有的结果集一次性提交而出现 数据量过大。
