### ISSUE TITLE
Syncer同步出错 panic: unreachable

### ISSUE THREAD

**Issue by vivithebest** [pingcap/docs-cn#725]
> 1. 我所做的操作

tidb-enterprise-tools-latest-linux-amd64/bin 目录下 `./syncer -config config.toml`

> 2. 预期结果

正确同步并输出info

> 3. 运行结果

```bash
[root@winterfell bin]# ./syncer -config config.toml
2018/05/11 09:40:27 main.go:52: [info] config: log-level:info log-file: log-rotate:day status-addr: server-id:101 worker-count:1 batch:1 meta-file:./syncer.meta do-tables:[{Schema:wms Name:~(^do_lack_detail$|^do_lack_header$|^doc_asn_detail$|^doc_asn_header$|^
doc_carton_detail$|^doc_carton_detail_his$|^doc_carton_header$|^doc_carton_header_his$|^doc_convert_detail$|^doc_convert_header$|^
doc_cou_detail$|^doc_cou_detail_batch$|^doc_cou_param$|^doc_do_detail$|^doc_do_detail_affix$|^doc_do_detail_his$|^doc_do_header$|^doc_do_header_his$|^doc_do_recheck$|^doc_do_wave_ex$|^doc_do_wave_ex_his$|^doc_exception_log$|^doc_gal_detail$|^doc_gal_header$|^d
oc_load_detail$|^doc_load_detail_his$|^doc_load_header$|^doc_load_header_his$|^doc_material_in_detail$|^doc_material_in_header$|^d
oc_material_out_detail$|^doc_material_out_header$|^doc_pack_material_log$|^doc_pack_material_log_his$|^doc_pkt_header$|^doc_pkt_header_his$|^doc_putaway_header$|^doc_receive_lack_reason$|^doc_receive_recheck_detail$|^doc_receive_recheck_header$|^doc_rp_header$
|^doc_rpl_header$|^doc_sub_receive_detail$|^doc_sub_receive_header$|^doc_wave_header$|^doc_wave_header_his$|^trs_package_log$|^trs
_putaway_task$|^trs_repl_move_task$|^trs_replenish_task$|^trs_reverse_pick_task$|^trs_ship_log$|^trs_ship_log_his$|^trs_transaction_log$|^trs_transaction_log_his$|^tsk_convert$|^tsk_pick$|^tsk_pick_his$)}] do-dbs:[] ignore-tables:[] ignore-dbs:[] from:DBConfig
(host:10.10.102.207, user:root, port:3306, pass:<omitted>) to:DBConfig(host:****, user:root, port:4000, pass:<omitted>) s
kip-ddls:[] skip-dmls:[] route-rules:[] enable-gtid:false safe-mode:false git-hash: adff8aa248abdf94715a667572c374afaf0aa187 utc-b
uild-time:[2018-05-04 11:41:04] go-version:go1.10
INFO[0000] create BinlogSyncer with config {101 mysql 10.10.102.207 3306 root    false false <nil> false 0 0s 0s}
INFO[0000] begin to sync binlog from position (mysql-bin.001959, 647617331)
INFO[0000] register slave for master server 10.10.102.207:3306
2018/05/11 09:40:27 syncer.go:831: [info] [syncer] last slave connection id 25394
INFO[0000] rotate to (mysql-bin.001959, 647617331)
2018/05/11 09:40:27 syncer.go:531: [info] rotate binlog to (mysql-bin.001959, 647617331)
2018/05/11 09:40:27 meta.go:120: [info] save position to file, binlog-name:mysql-bin.001959 binlog-pos:647617331 binlog-gtid:
2018/05/11 09:40:57 syncer.go:819: [info] [syncer]total events = 1230, total tps = 41, recent tps = 41, master-binlog = (mysql-bin
.001978, 95828501), master-binlog-gtid=, syncer-binlog = (mysql-bin.001959, 651966985), syncer-binlog-gtid =
2018/05/11 09:41:22 meta.go:120: [info] save position to file, binlog-name:mysql-bin.001959 binlog-pos:651977265 binlog-gtid:
2018/05/11 09:41:26 syncer.go:881: [info] flush all jobs meta = syncer-binlog = (mysql-bin.001959, 654463761), syncer-binlog-gtid
=
2018/05/11 09:41:27 syncer.go:819: [info] [syncer]total events = 2444, total tps = 40, recent tps = 40, master-binlog = (mysql-bin
.001978, 98372682), master-binlog-gtid=, syncer-binlog = (mysql-bin.001959, 654463761), syncer-binlog-gtid =
2018/05/11 09:41:51 meta.go:120: [info] save position to file, binlog-name:mysql-bin.001959 binlog-pos:654463761 binlog-gtid:
panic: unreachable

goroutine 63 [running]:
main.(*Syncer).addCount(0xc4203bc640, 0xc42009de06, 0x1)
        /home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.g
o:262 +0x260
main.(*Syncer).sync.func1()
        /home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.g
o:337 +0x164
main.(*Syncer).sync(0xc4203bc640, 0x7f3e92b07658, 0xc42031b140, 0xc4204301e0, 0xc4201133e0)
        /home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.g
o:381 +0x4b0
main.(*Syncer).run.func2(0xc4203bc640, 0x0)
        /home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.g
o:450 +0xa2
created by main.(*Syncer).run
        /home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.g
o:448 +0x313
```

> 4. 我的配置 config.toml

```
log-level = "info"

server-id = 101

## meta 文件地址
meta = "./syncer.meta"

worker-count = 1
batch = 1


[[replicate-do-table]]
db-name ="wms"
tbl-name = "~(^do_lack_detail$|^do_lack_header$|^doc_asn_detail$|^doc_asn_header$|^doc_carton_detail$|^doc_carton_detail_his$|^doc_carton_header$|^doc_carton_header_his$|^doc_convert_detail$|^doc_convert_header$|^doc_cou_detail$|^doc_cou_detail_batch$|^doc_cou_param$|^doc_do_detail$|^doc_do_detail_affix$|^doc_do_detail_his$|^doc_do_header$|^doc_do_header_his$|^doc_do_recheck$|^doc_do_wave_ex$|^doc_do_wave_ex_his$|^doc_exception_log$|^doc_gal_detail$|^doc_gal_header$|^doc_load_detail$|^doc_load_detail_his$|^doc_load_header$|^doc_load_header_his$|^doc_material_in_detail$|^doc_material_in_header$|^doc_material_out_detail$|^doc_material_out_header$|^doc_pack_material_log$|^doc_pack_material_log_his$|^doc_pkt_header$|^doc_pkt_header_his$|^doc_putaway_header$|^doc_receive_lack_reason$|^doc_receive_recheck_detail$|^doc_receive_recheck_header$|^doc_rp_header$|^doc_rpl_header$|^doc_sub_receive_detail$|^doc_sub_receive_header$|^doc_wave_header$|^doc_wave_header_his$|^trs_package_log$|^trs_putaway_task$|^trs_repl_move_task$|^trs_replenish_task$|^trs_reverse_pick_task$|^trs_ship_log$|^trs_ship_log_his$|^trs_transaction_log$|^trs_transaction_log_his$|^tsk_convert$|^tsk_pick$|^tsk_pick_his$)"

[from]
host = ""
user = "root"
password = ""
port = 3306

[to]
# 负载均衡地址
host = ""
user = "root"
password = ""
port = 4000
```
> 5. 版本信息

* syncer: v1.0.0~rc2+git.adff8aa
* MySQL: 5.6.33
* TiDB: v2.0.0-rc.4-87-gd6c0442

**Comment by datahoecn** [comment]
该问题已经修复，感谢您的反馈，请更新 master 分支版本替换

**Comment by vivithebest** [comment]
@datahoecn TiDB还是Syncer? 我刚才下载了Syncer，版本号是v1.0.0-3-g6da84a4，这个版本已经修复了对吧

**Comment by vivithebest** [comment]
it works！！！ thank you

**Comment by vivithebest** [comment]
it works！！！ thank you~
