### ISSUE TITLE
Wrong config value in ticdc confluent integration doc

### ISSUE THREAD

**Issue by zhangyangyu** [pingcap/docs-cn#8286]
## Error 报告

**This repository is ONLY used to solve problems related to DOCS-CN.
For other issues (TiDB, TiKV, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the document directory for the problem?

https://docs.pingcap.com/tidb/stable/integrate-confluent-using-ticdc#integration-procedures

2. How would you like to improve it?

The config example `jdbc-sink-connector.json` given in the doc could not work. The `"connection.url": "sqlite:test.db"` is wrong and will cause confluent connect to report:
```
[2022-02-07 10:25:50,779] ERROR [jdbc-sink-connector|task-0] WorkerSinkTask{id=jdbc-sink-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:206)
org.apache.kafka.connect.errors.ConnectException: Not a valid JDBC URL: sqlite:test.db
        at io.confluent.connect.jdbc.dialect.DatabaseDialects.extractJdbcUrlInfo(DatabaseDialects.java:175)
        at io.confluent.connect.jdbc.dialect.DatabaseDialects.findBestFor(DatabaseDialects.java:119)
        at io.confluent.connect.jdbc.sink.JdbcSinkTask.initWriter(JdbcSinkTask.java:64)
        at io.confluent.connect.jdbc.sink.JdbcSinkTask.start(JdbcSinkTask.java:50)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:313)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:197)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
A right value is like `jdbc:sqlite:/tmp/test.db`.

**Comment by TomShawn** [comment]
@liuzix Could you please take a look? Thanks!
